10 REM CALCULATOR SERVICE
20 INPUT X,Y,O$
30 IF O$="ADD" THEN PRINT X+Y
40 IF O$="SUB" THEN PRINT X-Y
50 IF O$="MUL" THEN PRINT X*Y
60 IF O$="DIV" THEN IF Y<>0 THEN PRINT X/Y
70 IF O$="POW" THEN PRINT X^Y
80 IF O$="MOD" THEN PRINT X-INT(X/Y)*Y
